### ISSUE TITLE
AccessDenied error on terraform init. 

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/terraform_scihist_digicoll#1]
I'm getting this error on terraform init:
```terraform init
Initializing the backend...
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: [redacted], host id: [redacted]
```

Running the `terraform init` prefixed with `TF_LOG=debug` reveals Terraform is attempting to use my default profile, which does not have the right credentials.

When I run:`aws configure list-profiles` I get:
```
	default
	admin
```

Workaround: when I run
`export AWS_ACCESS_KEY_ID=[redacted]` and `export AWS_SECRET_ACCESS_KEY=[redacted]`
with the credentials in my `admin` profile, I can run `terraform init` without any problems.

**Comment by jrochkind** [comment]
I just reproduced! 

(I had my "default" AWS profile also with sufficient auth, so I didn't notice it was using my default one instead of the admin one! When I made my default AWS profile a key without sufficient auth, I get an auth error too). 

Weird, have to figure out why the terraform provider isn't using the profile I thought I was telling it to.

**Comment by jrochkind** [comment]
Hm, the feature is possibly broken in terraform. As many users seem to be commenting on this issue, which is closed though. :( 

https://github.com/hashicorp/terraform/issues/18402

**Comment by jrochkind** [comment]
Wow it gets even crazier. You need to have env variable `AWS_SDK_LOAD_CONFIG` set to `true` for it to work???

https://github.com/hashicorp/terraform-provider-aws/pull/8451

Nope that still didn't make it work. I think this terraform feature is just broken. Which is problematic cause I don't know how else we do this, I really don't want superuser credentials in my aws default. 

Well, I guess you just need to always execute with `AWS_PROFLE=admin terraform whatever`? That works... I'm still researching

**Comment by eddierubeiz** [comment]
Just confirming that for me, once I pulled this PR, everything worked as documented in the modified readme.
