### ISSUE TITLE
Resolve S3-Bucket-Name tag discrepancies.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/terraform_scihist_digicoll#3]
Tag-related discrepancies with the `S3-Bucket-Name` tag under `tags` and `tag_resources` are making the output of `terraform plan` a lot noisier than it should be. We should either describe these tags in Terraform, or remove them from S3.

Take `aws_s3_bucket.public` as an example. Here's a redacted version of `terraform plan` 's output just for that one bucket:

```
  # aws_s3_bucket.public will be updated in-place
  ~ resource "aws_s3_bucket" "public" {
      ~ tags                        = {
          - "S3-Bucket-Name" = "scihist-digicoll-production-public" -> null
        }
      ~ tags_all                    = {
          - "S3-Bucket-Name" = "scihist-digicoll-production-public" -> null
        }
    }
```

**Comment by jrochkind** [comment]
Hey Chuck @CHF-IT-Staff , when going to add  `"S3-Bucket-Name"` tags to all buckets, I notice some discrepencies. Some of the existing tags have an initial space at the beginning of them, presumably an error. 

* `" scihist-digicoll-staging-ingest-mount"`
* ` " scihist-digicoll-staging-ondemand-derivatives"`

I am going to write the terraform config without the space, so after we run it it will change these tags to longer have a space. Please confirm this is acceptable/desirable?
