### ISSUE TITLE
Remove `ignore_changes` clauses from bucket definitions.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/terraform_scihist_digicoll#51]
This was only needed as a temporary bandaid while we were updating the bucket definitions to the latest version. It can and should be removed now, otherwise we will have trouble down the line.
The removal of these `ignore_changes` clauses will have no bearing on the actual buckets in AWS.

**Comment by jrochkind** [comment]
Thanks @eddierubeiz , I agree good to do this now!

**Comment by eddierubeiz** [comment]
Applied in staging and in production.
