### ISSUE TITLE
Manage scihist-digicoll IAM resources in Terraform

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/terraform_scihist_digicoll#6]
Ideally Terraform would manage:

- Users
- Groups
- Roles
- Policies
- Attachments between the above

See https://github.com/sciencehistory/export_archivesspace_xml/blob/main/terraform/s3.tf for some progress in this direction.

Low priority for now.

**Comment by jrochkind** [comment]
See also https://github.com/sciencehistory/scihist_digicoll/issues/1304 and https://github.com/sciencehistory/scihist_digicoll/issues/1295

**Comment by jrochkind** [comment]
Note that the current IAM policies for staging and production app user may include references buckets that don't exist/aren't used anymore; and also trigger warnings when looked at in the AWS console UI. They maybe need to be cleaned up.

**Comment by jrochkind** [comment]
Replaced by more specific tickets, referenced here.
