### ISSUE TITLE
Turn on logging for S3

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/terraform_scihist_digicoll#8]
There is a webserver-style logging feature for S3, that would give us more info on our S3 traffic, for figuring out the nature of our bandwidth costs. 

Logs are written to S3 location of your choice -- there is no additional charge but the S3 storage. 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html

We are currently only using CloudFront for our app assets -- which I don't think have been showing up in our costs as anything significant.  But we may want to do the same thing for that CloudFront distro now -- and we may use CloudFront in front of our asset S3 in the future. 

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html

**Comment by eddierubeiz** [comment]
I'll document and do some basic investigation of the resulting logs as part of this ticket.

**Comment by eddierubeiz** [comment]
(Production video originals too, as well.)

**Comment by eddierubeiz** [comment]
`terraform state show aws_s3_bucket.originals`
[...]
```
    logging {
        target_bucket = "chf-logs"
        target_prefix = "s3_server_access_staging_originals/"
    }
```
[...]

Likewise for video:

```
    logging {
        target_bucket = "chf-logs"
        target_prefix = "s3_server_access_staging_originals_video/"
    }
```
